version: '3.8'

services:
  bot:
    build: .
    container_name: english_bot
    restart: always
    env_file:
      - .env
    environment:
      # Փոխում ենք, որ միանա postgres սերվիսին (db)
      - DATABASE_URL=postgresql+asyncpg://bot_user:bot_password@db/english_bot_db
    volumes:
      - ./data:/app/data
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: english_bot_postgres
    restart: always
    environment:
      POSTGRES_USER: bot_user
      POSTGRES_PASSWORD: bot_password
      POSTGRES_DB: english_bot_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: